In [1]:
# NumPy

In [2]:
# Objective:
# The objective of this notebook is to learn the fundamentals of NumPy for numerical computing and to understand its application in biological data analysis.

In [ ]:
# Why is NumPy important in Bioinformatics?
# Modern bioinformatics involves analysing large biological datasets such as gene expression profiles, DNA sequences, protein measurements, and genomic variants. NumPy provides an efficient way to store, manipulate, and perform mathematical operations on these datasets using multidimensional arrays.
# Many popular scientific Python libraries, including Pandas, SciPy, scikit-learn, and Biopython, are built on top of NumPy. Therefore, understanding NumPy is an essential step towards performing advanced bioinformatics analyses and developing computational biology pipelines.

In [ ]:
# Topics covered:
# 1. Introduction to NumPy
# 2. Importing the NumPy library
# 3. Creating 1-D and multidimensional arrays
# 4. Array attributes (shape, size, dimensions and data types)
# 5. Reshaping arrays
# 6. Mathematical operations on arrays
# 7. Statistical functions (mean, median, standard deviation, minimum and maximum)
# 8. Indexing and slicing arrays
# 9. Working with rows, columns and axis operations
# 10. Handling missing values (NaN)

In [5]:
import numpy as np   # importing the library

In [ ]:
# Creating arrays

In [6]:
np_1 = np.array([1,2,3,4,5])
print(np_1)

[1 2 3 4 5]


In [7]:
# Create a numpy array of cubes of numbers 4-10

np_cubes = np.array([4,5,6,7,8,9,10])
print(np_cubes**3)

[  64  125  216  343  512  729 1000]


In [ ]:
print(type(np_cubes))   # printing type of numpy

<class 'numpy.ndarray'>


In [ ]:
## Converting a list into an array

a = [1,2,3,4,5]
type(a)
b = np.array(a)
type(b)

numpy.ndarray

In [ ]:
## Subsetting only the numbers divisible by 4.

np1 = np.array([1,2,3,4,5,6,7,8,9,10])
np.array([i for i in np1 if i % 4 ==0])

array([4, 8])

In [ ]:
subset = np.array([i for i in np1 if i % 4 != 0])
subset2 = subset - 1
print(subset)
print(subset2)

[ 1  2  3  5  6  7  9 10]
[0 1 2 4 5 6 8 9]


In [ ]:
# Reshaping array

In [ ]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(12).reshape(4,3)   ## Reshaping
                            ## reshape(number of rows, number of columns)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
natural_number = np.arange(1,101).reshape(4,25)
natural_number

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
natural_number.ndim

2

In [ ]:
nums = np.arange(1,19).reshape(3,6)
nums

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [ ]:
np_10 = np.array([23,24,25,26,27])
print(np_10)

[23 24 25 26 27]


In [ ]:
## Creating numpy array squares

np_squares = np.array([2,3,4,5,6])
print(np_squares ** 2)

[ 4  9 16 25 36]


In [ ]:
print(type(np_squares))

<class 'numpy.ndarray'>


In [ ]:
a = [10,20,30,40,50]
type(a)
c = np.array(a)
print(type(c))

<class 'numpy.ndarray'>


In [ ]:
# Subsetting only the numbers divided by 3

np_divisible= np.array([11,12,13,14,15,16,17,18,19,20,21])
np.array([i for i in np_divisible if i % 3 == 0])


array([12, 15, 18, 21])

In [ ]:
np_2 = ([10,20,35,43,45,50,67])
np.array([i for i in np_2 if i % 5 == 0])

array([10, 20, 35, 45, 50])

In [ ]:
# Subsetting

subset_1 = np.array([i for i in np_2 if i % 10 != 0])
subset_2 = subset_1 - 3
print(subset_1)
print(subset_2)

[35 43 45 67]
[32 40 42 64]


In [ ]:
subset_3 = subset_1 - 12
print(subset_3)

[23 31 33 55]


In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(4,11)

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [ ]:
np.arange(1,12,2).reshape(2,3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [ ]:
np.arange(3,13).reshape(2,5)

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [ ]:
nums = np.arange(1,9).reshape(2,4)
nums

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
nums.ndim

2

In [ ]:
nums_1 = np.arange(1,101).reshape(4,25)
nums_1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
nums_1.ndim

2

In [ ]:
numbers = np.array([5, 10, 15, 20, 25])
print(numbers)

[ 5 10 15 20 25]


In [ ]:
# Mathematical operations

In [ ]:
print(numbers + 10)
print(numbers * 3)

[15 20 25 30 35]
[15 30 45 60 75]


In [ ]:
gene_exp = np.array([12, 18, 25, 30, 40])
print(gene_exp.mean())
print(gene_exp.min())
print(gene_exp.max())

25.0
12
40


In [ ]:
arr = np.array([35, 42, 65])
print(arr ** 2)

[1225 1764 4225]


In [ ]:
# Indexing and Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])

10
50
[20 30 40]


In [ ]:
patients = np.array([101, 102, 103, 104, 105, 106])
print(patients[2:5])

[103 104 105]


In [ ]:
exp = np.array([5, 10, 15, 20, 25, 30])
print(exp[3])

20


In [ ]:
scores = np.array([
    [80, 75],
    [78, 93],
    [52, 76]
])
print(scores)
print(scores[1])
print(scores[2,1])
print(scores.shape)

[[80 75]
 [78 93]
 [52 76]]
[78 93]
76
(3, 2)


In [ ]:
scores = np.array([34, 53, 79, 67, 90, 43, 26])
print(scores > 50)
print(scores[scores > 50])

[False  True  True  True  True False False]
[53 79 67 90]


In [ ]:
exp = np.array([12, 18, 25, 35, 42, 50])
print(exp[exp < 30])

[12 18 25]


In [ ]:
patients = np.array([101, 102, 103, 104, 105])
print(patients[patients > 103])

[104 105]


In [ ]:
ages = np.array([18, 22, 35, 45, 60, 70])
print(ages[(ages > 20) & (ages < 50)])

[22 35 45]


In [ ]:
exp = np.array([5, 15, 25, 35, 45, 55])
print(exp[(exp < 10) | (exp > 50)])

[ 5 55]


In [ ]:
ages = np.array([18, 22, 35, 45, 60, 70])
print(ages[(ages < 20) | (ages > 50)])

[18 60 70]


In [ ]:
exp = np.array([10, 20, 30, 40, 50])
print(exp.sum())
print(exp.mean())
print(exp.min())
print(exp.max())
print(exp.std())
print(np.median(exp))

150
30.0
10
50
14.142135623730951
30.0


In [ ]:
fold_change = np.array([2.5, 3.1, 4.8, 5.2, 6.7])
print(fold_change.mean())
print(fold_change.std())
print(fold_change[fold_change > 4])

4.459999999999999
1.5081114017207087
[4.8 5.2 6.7]


In [ ]:
scores = np.array([
    [80, 75],
    [90, 88],
    [70, 95]
])
print(scores.sum(axis = 0))
print(scores.sum(axis = 1))
print(scores.mean(axis = 0))
print(scores.mean(axis = 1))

[240 258]
[155 178 165]
[80. 86.]
[77.5 89.  82.5]


In [ ]:
expression = np.array([
    [12, 18, 25],
    [15, 20, 30],
    [10, 22, 35]
])
print(expression.mean(axis = 0))
print(expression.mean(axis = 1))

[12.33333333 20.         30.        ]
[18.33333333 21.66666667 22.33333333]


In [ ]:
arr = np.arange(5, 16)
print(arr)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
arr = np.arange(5, 15, 3)
print(arr)

[ 5  8 11 14]


In [ ]:
arr = np.arange(0, 21, 5)
print(arr)

[ 0  5 10 15 20]


In [ ]:
# Zeros and Ones

In [ ]:
arr = np.zeros((4, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.ones((2, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
arr.reshape(3, 2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
# Handling missing values (NaN)

In [ ]:
arr = np.array([5, 10, np.nan, 25, 30, np.nan])
print(np.isnan(arr).sum())

2


In [ ]:
print(np.isnan(arr))

[False False  True False False  True]


In [ ]:
arr = np.array([12, 18, 25, 30, 40, 45])
arr.reshape(3,2)

array([[12, 18],
       [25, 30],
       [40, 45]])

In [ ]:
# Practice question

expression = np.array([
    [12, 18, 25, 30],
    [15, 20, 30, 35],
    [10, 22, 35, 40],
    [18, 25, 40, 45],
    [20, 30, 50, 55]
])

In [ ]:
print(expression.shape)

(5, 4)


In [ ]:
print(expression.mean(axis = 0))

[15. 23. 36. 41.]


In [ ]:
print(expression.mean(axis = 1))

[21.25 25.   26.75 32.   38.75]


In [ ]:
print(expression[expression > 35])

[40 40 45 50 55]


In [ ]:
gene_d = expression[:, 3]
print(gene_d[gene_d > 40])

[45 55]


In [ ]:
gene_c_d = expression[:, 2:4]
print(gene_c_d)
print(gene_c_d.shape)

[[25 30]
 [30 35]
 [35 40]
 [40 45]
 [50 55]]
(5, 2)


In [ ]:
raw = np.array([
12,18,25,30,
15,20,30,35,
10,22,35,40,
18,25,40,45,
20,30,50,55
])
new_data = raw.reshape(5, 4)
print(new_data)
print(new_data.shape)

[[12 18 25 30]
 [15 20 30 35]
 [10 22 35 40]
 [18 25 40 45]
 [20 30 50 55]]
(5, 4)


In [ ]:
expression.sum(axis = 1)

array([ 85, 100, 107, 128, 155])

In [ ]:
gene_d = expression[:, 3]
print(gene_d)
average_gene_d = gene_d.mean()
print(average_gene_d)

gene_a = expression[:, 0]
print(gene_a)
average_gene_a = gene_a.mean()
print(average_gene_a)

print(average_gene_d / average_gene_a)

[30 35 40 45 55]
41.0
[12 15 10 18 20]
15.0
2.7333333333333334


In [ ]:
# Summary

# After completing this notebook, I can:
# - Create and manipulate NumPy arrays
# - Perform mathematical operations on biological datasets
# - Reshape multidimensional arrays
# - Calculate descriptive statistics
# - Apply indexing, slicing and Boolean filtering
# - Handle missing values in numerical datasets
# - Prepare biological data for further analysis using Pandas and machine learning libraries

# This notebook establishes the numerical computing foundation required for learning Pandas, data visualisation, machine learning, and advanced bioinformatics workflows.